### ISSUE TITLE
Crash when opening eldritch manuscript with innate_unlocks_eldritch set to true

### ISSUE THREAD

**Issue by PvtFudgepants** [SiverDX/additional_attributes#6]
As the title says, if you open the Eldritch Manuscript from iron's spellbooks while the config in this mod "innate_unlocks_eldritch" is set to true, the game crashes instantly.

**Comment by SiverDX** [comment]
can't reproduce that issue (1.21, latest iss version)
you're going to need to post some logs

**Comment by PvtFudgepants** [comment]
Ah sorry, forgot to mention I was on 1.20.1. Not sure if you're still updating that or not.
Here's the log
[crash-2024-12-21_21.39.42-client.txt](https://github.com/user-attachments/files/18220594/crash-2024-12-21_21.39.42-client.txt)
